
export enum DialectFeatures
{
  WITH                    = 0,
  WITH_RECURSIVE          = 1,
  AGGREGATE_OVER          = 2,
  AGGREGATE_DISTINCT      = 3,
  AGGREGATE_ORDER         = 4,
  AGGREGATE_FILTER        = 5,
  SELECT_DISTINCT_ON      = 6,
  SELECT_LATERAL_SUBQUERY = 7,
  ROW_CONSTRUCTOR         = 8,
  PREDICATE_LIST          = 9,
  WINDOWS                 = 10,
  GROUP_BY_SET            = 11,
  LOCK                    = 12,
  LOCK_TABLE              = 13,
  LOCK_ROW                = 14,
  ORDER_NULLS             = 15,
  DELETE_USING            = 16,
  DELETE_RETURNING        = 17,
  INSERT_PRIORITY         = 18,
  INSERT_IGNORE_DUPLICATE = 19,
  JSON                    = 20,
  INSERT_SET_ON_DUPLICATE = 21,
  INSERT_RETURNING        = 22,
  UPDATE_MULTISET         = 23,
  UPDATE_FROM             = 24,
  UPDATE_RETURNING        = 25,
  DEFAULT                 = 26,
  ARRAYS                  = 27,
  UNSIGNED                = 28,
  NAMED_PARAMETERS        = 29,
  FUNCTION_NAMED_PARAMS   = 30,
  LATERAL_JOIN            = 31,
  ALIASED_UPDATE_DELETE   = 32,

  ALL                     = -1,
}

export const DialectFeaturesDescription = 
[
  '',
  'WITH clause (common table expression)',
  'WITH RECURSIVE clause (common table expression)',
  'Aggregate OVER clause',
  'Aggregate DISTINCT clause',
  'Aggregate ORDER BY clause',
  'Aggregate FILTER clause',
  'SELECT DISTINCT ON clause',
  'LATERIAL subquery',
  'ROW constructor',
  'ANY/ALL predicate',
  'Window Functions',
  'Group By GROUPING SET/ROLLUP/CUBE',
  'SELECT LOCK',
  'SELECT LOCK specific table',
  'SELECT row level LOCK',
  'Order NULLS FIRST/LAST',
  'DELETE USING clause',
  'DELETE RETURNING clause',
  'INSERT priority',
  'INSERT ignore duplicate',
  'JSON expressions',
  'INSERT on duplicate key set clause',
  'INSERT RETURNING clause',
  'UPDATE multi-set',
  'UPDATE FROM clause',
  'UPDATE RETURNING',
  'DEFAULT expression',
  'ARRAY data types',
  'UNSIGNED numeric types',
  'named parameters',
  'named parameters in functions',
  'LATERAL/APPLY joins',
  'UPDATE/DELETE with aliased table'
]; 