CREATE DATABASE tqb;
USE tqb;
CREATE TABLE [Group] (
  [ID] INT NOT NULL IDENTITY,
  [Name] NVARCHAR(128) NOT NULL,
  PRIMARY KEY ([ID])
);
CREATE TABLE [Person] (
  [ID] INT NOT NULL IDENTITY,
  [Name] NVARCHAR(128) NOT NULL,
  [Email] NVARCHAR(128) NOT NULL,
  [Location] GEOMETRY,
  PRIMARY KEY ([ID])
);
CREATE TABLE [PersonGroup] (
  [GroupID] INT NOT NULL,
  [PersonID] INT NOT NULL,
  [Status] SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY ([GroupID], [PersonID]),
  FOREIGN KEY ([GroupID]) REFERENCES [Group] ON DELETE CASCADE,
  FOREIGN KEY ([PersonID]) REFERENCES [Person] ON DELETE CASCADE
);
CREATE TABLE [Task] (
  [ID] INT NOT NULL IDENTITY,
  [GroupID] INT NOT NULL,
  [Name] NVARCHAR(128) NOT NULL,
  [Details] NVARCHAR(MAX) NOT NULL,
  [Done] BIT NOT NULL DEFAULT 0,
  [DoneAt] DATETIME2 NULL,
  [ParentID] INT NULL,
  [AssignedTo] INT NULL,
  [AssignedAt] DATETIME2 NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  [CreatedBy] INT NULL,
  PRIMARY KEY ([ID]),
  FOREIGN KEY ([GroupID]) REFERENCES [Group] ON DELETE CASCADE,
  FOREIGN KEY ([ParentID]) REFERENCES [Task] ON DELETE NO ACTION,
  FOREIGN KEY ([AssignedTo]) REFERENCES [Person] ON DELETE SET NULL,
  FOREIGN KEY ([CreatedBy]) REFERENCES [Person] ON DELETE NO ACTION
);