
export const enum ExprKind {
    AGGREGATE               = 'agg',
    BETWEEN                 = 'btwn',
    CASE                    = 'case',
    CAST                    = 'cast',   
    CONDITION_BINARY        = 'a?b',
    CONDITION_BINARY_LIST   = 'a?l',
    CONDITIONS              = 'andor',
    CONDITION_UNARY         = 'a?',
    CONSTANT               = 'const',
    DEFAULT                 = 'def',
    EXISTS                  = 'exist',
    FIELD                   = 'field',
    FUNCTION                = 'func',
    IN                      = 'in',
    NOT                     = 'not',
    OPERATION_BINARY        = 'a+b',
    OPERATION_UNARY         = '-a',
    PARAM                   = 'param',
    RAW                     = 'raw',
    ROW                     = 'row',
    JOIN                    = 'join',
    VALUES                  = 'values',
    TABLE                   = 'table',
    TABLE_UNSPECIFIED       = 'table?',
    QUERY_SELECT            = 'sel',
    QUERY_EXISTENTIAL       = '1',
    QUERY_FIRST             = 'first',
    QUERY_FIRST_VALUE       = 'value',
    QUERY_LIST              = 'list',
    QUERY_RECURSIVE         = 'recur',
    QUERY_INSERT            = 'ins',
    QUERY_UPDATE            = 'upd',
    QUERY_DELETE            = 'del',
    QUERY_SET_OPERATION     = 'set',
}